{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-helm.fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0] }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nginx-helm.fullname" . }}
                port:
                  number: 80
{{- end }}
